name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm install
        name: Install npm packages
      - name: Tell git who I am
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"
      - run: npm run build
        name: Build application
      - run: node build/app.js install
        name: Install packages
      - run: npm run test
        name: Run test script
